#!/bin/bash
# vim: set ts=4:
set -o errexit

cd "$(dirname "$0")/.."

echo '==> Importing SQL schema to MySQL'

mysql -e 'create database spring_data_jdbc_repository_test;' || true
mysql spring_data_jdbc_repository_test < src/test/resources/schema_mysql.sql
