#!/bin/bash
# vim: set ts=4:
set -o errexit

cd "$(dirname "$0")/.."

echo '==> Importing SQL schema to PostgreSQL'

psql -c 'create database spring_data_jdbc_repository_test;' -U postgres || true
psql spring_data_jdbc_repository_test < src/test/resources/schema_postgresql.sql
