#!/bin/bash
# vim: set ts=4:
set -o errexit

cd "$(dirname "$0")/.."

case "$DB" in
	postgresql)
		psql -U postgres -c 'create database spring_data_jdbc_repository_test;'
	;;
	mariadb | mysql)
		mysql -e 'create database spring_data_jdbc_repository_test;'
	;;
	oracle)
		# Workaround for nasty buffer overflow
		# https://github.com/travis-ci/travis-ci/issues/5227
		sudo hostname "$(hostname | cut -c1-63)"
		sed -e "s/^\(127\.0\.0\.1.*\)/\1 $(hostname | cut -c 1-63)/" /etc/hosts \
			| sudo tee /etc/hosts

		script/travis-install-oracle

		# import schema
		echo exit | "$ORACLE_HOME"/bin/sqlplus test/test @src/test/resources/schema_oracle.sql
	;;
esac
